import type { Listing } from './types';

export const DEMO_LISTINGS: Listing[] = [
  {
    id: 1,
    supplier: 'Salom Bakery',
    category: 'bakery',
    title: 'Assorted Pastry Box',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
    originalPrice: 45000,
    discountedPrice: 22500,
    discount: 50,
    expiresIn: '3 hours',
    expiresInHours: 3,
    pickup: '17:00–19:00',
    descriptions: {
      uz: 'Kruassanlar, shokoladli bulochkalar, daniyacha pishiriqlar va ertalabki nonlardan iborat yangi pishirilgan pishiriqlar to\'plami. Har kuni yangi tayyorlanadi — ulguring!',
      ru: 'Восхитительный набор свежей выпечки: круассаны, шоколадные булочки, датские завитушки и утренние булочки. Свежая выпечка каждый день — успейте забрать!',
      en: 'A delightful assortment of freshly baked pastries including croissants, pain au chocolat, Danish twists, and morning buns. Baked fresh daily — grab them before they\'re gone!',
    },
  },
  {
    id: 2,
    supplier: 'Green Market',
    category: 'supermarket',
    title: 'Fresh Salad Mix',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    originalPrice: 35000,
    discountedPrice: 17500,
    discount: 50,
    expiresIn: '5 hours',
    expiresInHours: 5,
    pickup: '15:00–17:00',
    descriptions: {
      uz: 'Mavsumiy ko\'katlar, gilos pomidorlari, bodring, qizil piyoz va yangi o\'tlardan iborat salat to\'plami. Mahalliy yetishtirilgan, yuvilgan va iste\'molga tayyor.',
      ru: 'Свежий салатный микс из сезонной зелени, черри-помидоров, огурца, красного лука и свежей зелени. Местного производства, вымыт и готов к подаче.',
      en: 'A vibrant salad mix of seasonal greens, cherry tomatoes, cucumber, red onion, and fresh herbs. Sourced locally, washed and ready to serve.',
    },
  },
  {
    id: 3,
    supplier: 'La Piazza',
    category: 'restaurant',
    title: 'Margherita Pizza',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop',
    originalPrice: 80000,
    discountedPrice: 48000,
    discount: 40,
    expiresIn: '2 hours',
    expiresInHours: 2,
    pickup: '20:00–21:00',
    descriptions: {
      uz: 'San-Martsano pomidor sousi, yangi mozzarella va rayhon bilan tayyorlangan klassik neapolitan Margherita pizza. O\'tin pechida pishirilgan. Bir qutida bitta 32 sm pizza.',
      ru: 'Классическая неаполитанская пицца Маргарита с соусом Сан-Марцано, свежей моцареллой и базиликом. Приготовлена в дровяной печи. Одна пицца 32 см в коробке.',
      en: 'A classic Neapolitan Margherita pizza with San Marzano tomato sauce, fresh mozzarella, and basil. Made in a wood-fired oven. One 32cm pizza per box.',
    },
  },
  {
    id: 4,
    supplier: 'Magnit UZ',
    category: 'supermarket',
    title: 'Yogurt Variety Pack',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop',
    originalPrice: 28000,
    discountedPrice: 14000,
    discount: 50,
    expiresIn: '6 hours',
    expiresInHours: 6,
    pickup: '18:00–20:00',
    descriptions: {
      uz: 'Tabiiy, qulupnay, shaftoli va vanil ta\'mlarida 6 ta premium yogurt to\'plami. Muddati ertaga tugaydi, ammo hali mukammal yangi.',
      ru: 'Набор из 6 премиальных йогуртов в разных вкусах — натуральный, клубничный, персиковый и ванильный. Срок годности до завтра, но абсолютно свежие.',
      en: 'A selection of 6 premium yogurts in assorted flavors — natural, strawberry, peach, and vanilla. Best before tomorrow, still perfectly fresh.',
    },
  },
  {
    id: 5,
    supplier: 'Shifo Dorixona',
    category: 'pharmacy',
    title: 'Vitamin C Bundle',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop',
    originalPrice: 55000,
    discountedPrice: 33000,
    discount: 40,
    expiresIn: '4 hours',
    expiresInHours: 4,
    pickup: '16:00–18:00',
    descriptions: {
      uz: 'Yuqori sifatli C vitamini qo\'shimchalari to\'plami — 500mg ko\'piklanadigan tabletkalardan 3 paket. Muddati yaqinlashgan, ammo to\'liq samarali. Immunitetni mustahkamlash uchun ajoyib.',
      ru: 'Набор высококачественных добавок с витамином C — 3 упаковки шипучих таблеток по 500 мг. Близко к сроку годности, но полностью эффективны. Отличное предложение для поддержки иммунитета.',
      en: 'A bundle of high-quality Vitamin C supplements — 3 packs of 500mg effervescent tablets. Near best-before date but fully effective. A great deal for immunity support.',
    },
  },
  {
    id: 6,
    supplier: 'Coffee House',
    category: 'cafe',
    title: 'Croissant + Latte',
    image: 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=400&h=300&fit=crop',
    originalPrice: 42000,
    discountedPrice: 25200,
    discount: 40,
    expiresIn: '3 hours',
    expiresInHours: 3,
    pickup: '17:00–19:00',
    descriptions: {
      uz: 'Katta yoki oddiy latte bilan birlashtirilgan yangi pishirilgan sariyog\'li kruassan. Kechki yopilish vaqtigacha mavjud — tushdan keyingi ajoyib siyliq.',
      ru: 'Свежеиспечённый круассан на сливочном масле в паре с большим овсяным или обычным латте. Доступно до закрытия — идеальное послеполуденное угощение.',
      en: 'A freshly baked all-butter croissant paired with a large oat or regular latte. Available until closing time — the perfect afternoon treat.',
    },
  },
  {
    id: 7,
    supplier: 'Dolce Vita',
    category: 'cafe',
    title: 'Tiramisu Box (4 pcs)',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop',
    originalPrice: 65000,
    discountedPrice: 39000,
    discount: 40,
    expiresIn: '2 hours',
    expiresInHours: 2,
    pickup: '18:00–20:00',
    descriptions: {
      uz: 'Alohida kosachalarda 4 ta qo\'lda tayyorlangan tiramisu porsiyasi. Maskarpone, espressoga botirilib tayyorlangan savoiardi va premium kakao bilan tayyorlangan. Sovuqda iste\'mol qilish tavsiya etiladi.',
      ru: 'Четыре порции ручного тирамису в индивидуальных стаканчиках. Приготовлено из маскарпоне, дамских пальчиков, пропитанных эспрессо, и посыпано качественным какао. Лучше всего в охлаждённом виде.',
      en: 'Four handmade tiramisu portions in individual cups. Made with mascarpone, espresso-soaked ladyfingers, and a dusting of premium cocoa. Best enjoyed chilled.',
    },
  },
  {
    id: 8,
    supplier: 'Sabzavot Bozor',
    category: 'store',
    title: 'Seasonal Fruit Box',
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&h=300&fit=crop',
    originalPrice: 40000,
    discountedPrice: 20000,
    discount: 50,
    expiresIn: '8 hours',
    expiresInHours: 8,
    pickup: '10:00–18:00',
    descriptions: {
      uz: 'Mavsumiy mevalar to\'plami — tarvuz, shaftoli, o\'rik va mahalliy o\'zbek fermerlik xo\'jaliklaridan uzum. Qo\'l bilan terilgan va iste\'molga tayyor. Butun oila uchun ajoyib.',
      ru: 'Тщательно подобранная коробка сезонных фруктов — арбуз, персики, абрикосы и виноград с местных узбекских ферм. Собраны вручную и готовы к употреблению. Отлично для всей семьи.',
      en: 'A curated box of seasonal fruits — watermelon, peaches, apricots, and grapes from local Uzbek farms. Hand-picked and ready to eat. Perfect for the whole family.',
    },
  },
  {
    id: 9,
    supplier: 'Orient Bakery',
    category: 'bakery',
    title: 'Sourdough Bread Pack',
    image: 'https://images.unsplash.com/photo-1549931319-a545753467c8?w=400&h=300&fit=crop',
    originalPrice: 30000,
    discountedPrice: 18000,
    discount: 40,
    expiresIn: '4 hours',
    expiresInHours: 4,
    pickup: '15:00–17:00',
    descriptions: {
      uz: 'Bu ertalab pishirilgan qattiq po\'stloq va yumshoq ichli ikkita katta achitqi non. Konservantlarsiz — faqat un, suv, tuz va achitqi. Sariyog\' yoki pishloq bilan juda mazali.',
      ru: 'Два больших хлеба на закваске, выпеченных сегодня утром — хрустящая корочка и нежная мякоть. Без консервантов: только мука, вода, соль и закваска. Прекрасно со сливочным маслом или сыром.',
      en: 'Two large sourdough loaves baked this morning with a crispy crust and chewy interior. No preservatives — just flour, water, salt, and starter. Great with butter or cheese.',
    },
  },
  {
    id: 10,
    supplier: 'Pharmaline',
    category: 'pharmacy',
    title: 'Omega-3 Bundle',
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&h=300&fit=crop',
    originalPrice: 75000,
    discountedPrice: 45000,
    discount: 40,
    expiresIn: '5 hours',
    expiresInHours: 5,
    pickup: '14:00–16:00',
    descriptions: {
      uz: 'Yuqori sifatli Omega-3 baliq yog\'i kapsulalaridan 3 paket to\'plami. Muddati yaqinlashgan, ammo oziqaviy sifatlari to\'liq saqlanib qolgan. Yurak va miya salomatligi uchun ajoyib narx.',
      ru: 'Набор из 3 упаковок высококачественных капсул с рыбьим жиром Омега-3. Близко к сроку годности, но пищевая ценность полностью сохранена. Отличная цена для здоровья сердца и мозга.',
      en: 'A bundle of 3 packs of high-quality Omega-3 fish oil capsules. Near best-before date but nutritionally intact. Excellent value for heart and brain health.',
    },
  },
  {
    id: 11,
    supplier: 'Tandoor House',
    category: 'restaurant',
    title: 'Mixed Kebab Set',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop',
    originalPrice: 120000,
    discountedPrice: 72000,
    discount: 40,
    expiresIn: '1 hour',
    expiresInHours: 1,
    pickup: '21:00–22:00',
    descriptions: {
      uz: 'Lavash non, grillda pishirilgan pomidorlar va piyoz salatasi bilan yangi qovurilgan qo\'y va tovuq kebabi assortisi. Buyurtmaga tayyorlanadi, issiq holda beriladi.',
      ru: 'Ассорти из свежеприготовленных шашлыков из баранины и курицы с лавашом, запечёнными помидорами и луковым салатом. Готовится по заказу, подаётся горячим.',
      en: 'An assorted platter of freshly grilled lamb and chicken kebabs with lavash bread, grilled tomatoes, and onion salad. Prepared to order, served hot.',
    },
  },
  {
    id: 12,
    supplier: 'Smart Market',
    category: 'supermarket',
    title: 'Dairy Essentials Box',
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=400&h=300&fit=crop',
    originalPrice: 50000,
    discountedPrice: 25000,
    discount: 50,
    expiresIn: '7 hours',
    expiresInHours: 7,
    pickup: '16:00–18:00',
    descriptions: {
      uz: 'Sut mahsulotlari to\'plami: to\'liq yog\'li sut (1L), qaymoq (400g), qishloq peniri va sariyog\'. Barcha mahsulotlar muddati yaqinlashgan — pishirish yoki kundalik foydalanish uchun ideal.',
      ru: 'Набор молочных продуктов первой необходимости: цельное молоко (1 л), сметана (400 г), творог и сливочное масло. Все продукты близко к сроку годности — идеально для выпечки или ежедневного использования.',
      en: 'A curated box of dairy staples: whole milk (1L), sour cream (400g), farmer\'s cheese, and butter. All items near best-before date — perfect for baking or daily use.',
    },
  },
];
